In [168]:
import numpy as np
import pandas as pd

In [169]:
# Here we are loading the dataset, that has been proceesed through mobilenetv2 from
# layer block_14_add
# membership and distrobution of training, validation, and test set are pre determined via pseudo random methods
ABG_training_data2 = pd.read_csv("block_14_add_training_set.csv")
ABG_training_data = pd.read_csv("mobnet_block_14_add_features_OverSampledDataSplit_seed3_train.csv")
ABG_validation_data = pd.read_csv("block_14_add_validation_data.csv")
ABG_testing_data = pd.read_csv("block_14_add_testing_feature.csv")

In [170]:
# dropping all unknown values from the dataset
ABG_training_data = ABG_training_data.dropna()
ABG_validation_data = ABG_validation_data.dropna()
ABG_testing_data = ABG_testing_data.dropna()

In [171]:
#  The UMAP fit function only takes in numerical/char labels for this reason
#  In this csv file, 
#   Anthrophony is labeled as 1
#   Biophony is labeled as 2
#   Geophony is labeled as 3
#   Other is labeled as 4

In [172]:
ABG_training_data.Label.value_counts()  # number of datapoints in each class in training set

1    3086
2    3086
3    3086
4    3086
Name: Label, dtype: int64

In [173]:
ABG_validation_data.Label.value_counts()  # number of datapoints in each class in validation set

1    200
2    200
3    200
4     50
Name: Label, dtype: int64

In [174]:
ABG_testing_data.Label.value_counts()  # number of datapoints in each class in testing set

1    50
2    50
3    50
4    50
Name: Label, dtype: int64

In [175]:
from sklearn.preprocessing import StandardScaler  

In [176]:
scaler = StandardScaler().fit(ABG_training_data.drop("Label", axis = 1))  # normalizing based on training data 

In [177]:
# applying the normalization to the other datapoints 
scaled_training_set   = scaler.transform(ABG_training_data.drop("Label", axis = 1))    
scaled_validation_set = scaler.transform(ABG_validation_data.drop("Label", axis = 1))
scaled_testing_set    = scaler.transform(ABG_testing_data.drop("Label", axis = 1))

In [178]:
trainingDataLabel = [''] * 12344  # creating char labels that UMAP can accept 
for i in range(0,3086):
    trainingDataLabel[i] = 'A'
for i in range(3086,6172):
    trainingDataLabel[i] = 'B'
for i in range(6172,9258):
    trainingDataLabel[i] = 'G'
for i in range(9258,12344):
    trainingDataLabel[i] = 'O'

In [179]:
ValidationDataLabel = [''] * 650  # creating char labels that UMAP can accept 
for i in range(0,200):
    ValidationDataLabel[i] = 'A'
for i in range(200,400):
    ValidationDataLabel[i] = 'B'
for i in range(400,600):
    ValidationDataLabel[i] = 'G'
for i in range(600,650):
    ValidationDataLabel[i] = 'O'

In [180]:
testDataLabel = [''] * 200  # creating char labels that UMAP can accept 
for i in range(0,50):
    testDataLabel[i] = 'A'
for i in range(50,100):
    testDataLabel[i] = 'B'
for i in range(100,150):
    testDataLabel[i] = 'G'
for i in range(150,200):
    testDataLabel[i] = 'O'

In [181]:
combinedLabel = trainingDataLabel + ValidationDataLabel;  # combining labels for cross-validation for gridsearch

In [182]:
import umap  
reducer   = umap.UMAP(random_state=42, n_components=4, n_neighbors=15, min_dist = 0.25)  # init umap and set param
embedding = reducer.fit(scaled_training_set, trainingDataLabel)  # this is where umap learns about our data
# through supervised learning

# From here umap applies the metrics it learned from the data set to the rest of the data set
Training_Embedding   = reducer.transform(scaled_training_set) 
Validation_Embedding = reducer.transform(scaled_validation_set)
Testing_Embedding    = reducer.transform(scaled_testing_set)

/Users/jcalderonchavez/opt/miniconda3/lib/python3.8/site-packages/umap/umap_.py:2449: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  y_ = check_array(y, ensure_2d=False)[index]
/Users/jcalderonchavez/opt/miniconda3/lib/python3.8/site-packages/scipy/sparse/_index.py:126: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


inside function
   (0, 317)	0.2568219
  (0, 536)	0.32978076
  (0, 806)	0.25450936
  (0, 890)	0.26361617
  (0, 1214)	0.2584386
  (0, 1303)	0.2584386
  (0, 1709)	0.32978076
  (0, 1732)	0.25450936
  (0, 2035)	0.25450936
  (0, 2261)	0.3273826
  (0, 2513)	0.27723306
  (0, 2680)	0.3273826
  (0, 2881)	0.3273826
  (0, 2905)	0.2584386
  (0, 2999)	0.2584386
  (1, 108)	0.28642863
  (1, 1830)	0.23417212
  (1, 2017)	0.30710205
  (1, 2481)	0.26012984
  (1, 2992)	0.24828565
  (1, 3150)	0.27734432
  (1, 3362)	0.27734432
  (1, 3918)	0.26779887
  (1, 4163)	0.25718877
  (1, 4340)	0.37533334
  :	:
  (648, 6813)	0.2769064
  (648, 7559)	0.2829548
  (648, 7629)	0.27405944
  (648, 7892)	0.27405944
  (648, 7952)	0.2849711
  (648, 8278)	0.2829548
  (648, 8383)	0.2769064
  (648, 8679)	0.2829548
  (648, 9041)	0.2769064
  (648, 9153)	0.27405944
  (649, 3196)	0.22660024
  (649, 6596)	0.23337348
  (649, 7127)	0.23337348
  (649, 9397)	0.27810013
  (649, 10321)	0.3295839
  (649, 10464)	0.3295839
  (649, 10718)	0.27810

In [183]:
combined_data = np.vstack((Training_Embedding, Validation_Embedding)) # combining labels for cross-validation for gridsearch

In [184]:
inValidation = [0] * 12994  # here we are distingishing which datapoint of in the validation set
for i in range(0, 12343):
    inValidation[i] = -1
    
for i in range(12344, 12993):
    inValidation[i] = 0    

In [185]:
from sklearn.model_selection import PredefinedSplit
ps = PredefinedSplit(test_fold=inValidation)

In [186]:
from sklearn.model_selection import GridSearchCV 
from sklearn.model_selection import cross_validate
from sklearn.svm import SVC

# defining parameter range 
param_grid = {'C': [0.1, 1, 10, 100, 1000],  
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
              'kernel': ['rbf'], 
              'probability': [True]
             }  
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3, cv=ps) 
  
# fitting the model for grid search 
grid.fit(combined_data, combinedLabel) 

Fitting 1 folds for each of 25 candidates, totalling 25 fits
[CV] C=0.1, gamma=1, kernel=rbf, probability=True ....................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  C=0.1, gamma=1, kernel=rbf, probability=True, score=0.724, total=   8.5s
[CV] C=0.1, gamma=0.1, kernel=rbf, probability=True ..................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    8.5s remaining:    0.0s


[CV]  C=0.1, gamma=0.1, kernel=rbf, probability=True, score=0.722, total=   5.0s
[CV] C=0.1, gamma=0.01, kernel=rbf, probability=True .................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   13.5s remaining:    0.0s


[CV]  C=0.1, gamma=0.01, kernel=rbf, probability=True, score=0.693, total=   6.1s
[CV] C=0.1, gamma=0.001, kernel=rbf, probability=True ................
[CV]  C=0.1, gamma=0.001, kernel=rbf, probability=True, score=0.622, total=  13.5s
[CV] C=0.1, gamma=0.0001, kernel=rbf, probability=True ...............
[CV]  C=0.1, gamma=0.0001, kernel=rbf, probability=True, score=0.524, total=  22.8s
[CV] C=1, gamma=1, kernel=rbf, probability=True ......................
[CV]  C=1, gamma=1, kernel=rbf, probability=True, score=0.724, total=   3.4s
[CV] C=1, gamma=0.1, kernel=rbf, probability=True ....................
[CV]  C=1, gamma=0.1, kernel=rbf, probability=True, score=0.722, total=   2.3s
[CV] C=1, gamma=0.01, kernel=rbf, probability=True ...................
[CV]  C=1, gamma=0.01, kernel=rbf, probability=True, score=0.705, total=   4.4s
[CV] C=1, gamma=0.001, kernel=rbf, probability=True ..................
[CV]  C=1, gamma=0.001, kernel=rbf, probability=True, score=0.665, total=   8.2s
[CV] C=1

[Parallel(n_jobs=1)]: Done  25 out of  25 | elapsed:  3.7min finished


GridSearchCV(cv=PredefinedSplit(test_fold=array([-1, -1, ...,  0,  0])),
             error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf'], 'probability': [True]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [187]:
# print how our model looks after hyper-parameter tuning 
print(grid.best_estimator_) 

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)


In [188]:
# print best parameter after tuning 
print(grid.best_params_) 

{'C': 0.1, 'gamma': 1, 'kernel': 'rbf', 'probability': True}


In [189]:
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.metrics import accuracy_score

grid_predictions = grid.predict(Testing_Embedding) 
print(classification_report(testDataLabel, grid_predictions)) # print classification report 
print(accuracy_score(testDataLabel, grid_predictions))

              precision    recall  f1-score   support

           A       0.93      0.76      0.84        50
           B       0.76      0.84      0.80        50
           G       0.83      0.80      0.82        50
           O       0.79      0.88      0.83        50

    accuracy                           0.82       200
   macro avg       0.83      0.82      0.82       200
weighted avg       0.83      0.82      0.82       200

0.82


In [190]:
print(confusion_matrix(testDataLabel, grid_predictions)) # c matrix

[[38  9  2  1]
 [ 1 42  2  5]
 [ 1  3 40  6]
 [ 1  1  4 44]]
